name: Base Deploy Package

on: workflow_call

jobs:
  base-deploy-package:
    name: Base Deploy Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
