name: Deploy Package to @next

on:
  push:
    branches:
      - main
    paths:
      - src/**/*.ts

jobs:
  deploy-next-package:
    uses: ./.github/workflows/base-deploy-package.yml
    with:
      tag: next
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
