name: Deploy Package

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: choice
        options:
          - latest
          - next

jobs:
  deploy-package:
    uses: ./.github/workflows/base-deploy-package.yml
    with:
      tag: next
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
