name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest

    outputs:
      release-created: ${{ steps.release-please.outputs.release_created }}

    steps:
      - name: Release Please
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          package-name: gwitch
          release-type: node

  deploy-next-package:
    name: Deploy Package
    if: ${{ needs.release-please.outputs.release-created }}
    needs: release-please
    uses: ./.github/workflows/base-deploy-package.yml
    with:
      tag: latest
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
